{{- if .Values.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "microservice.fullname" . }}-migration
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrationJob.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "microservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.migrationJob.image.repository | default .Values.image.repository }}:{{ .Values.migrationJob.image.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.migrationJob.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrationJob.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.configMap.enabled .Values.externalSecret.enabled }}
          envFrom:
            {{- if .Values.configMap.enabled }}
            - configMapRef:
                name: {{ include "microservice.fullname" . }}-config
            {{- end }}
            {{- if .Values.externalSecret.enabled }}
            - secretRef:
                name: {{ default (printf "%s-secret" (include "microservice.fullname" .)) .Values.externalSecret.target.name }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.migrationJob.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.tmpDirs }}
            - name: tmp-{{ . | replace "/" "-" | trimPrefix "-" }}
              mountPath: {{ . }}
            {{- end }}
      volumes:
        {{- range .Values.tmpDirs }}
        - name: tmp-{{ . | replace "/" "-" | trimPrefix "-" }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
