{{- if .Values.nginxConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice.fullname" . }}-nginx
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
data:
  default.conf: |
    {{- .Values.nginxConfig.config | nindent 4 }}
{{- end }}
